name: dis-test
channels:
  - defaults
dependencies:
  - pytest=7.1.1
  - scikit-learn==1.0.2
  - python=3.10
  - pytorch=1.10.2
  - pip=21.2.4
  - pip:
    - pre-commit==2.17.0
    - matplotlib==3.5.2
    - seaborn==0.11.2
    - pandas==1.4.3
    - sdeint==0.3.0
    - functorch==0.2.1
